server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: smartsave-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: smartsave-app
          __path__: /var/log/smartsave/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
      - labels:
          level:
          job:
      - timestamp:
          source: timestamp
          format: RFC3339

  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          type: access
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<request>[^"]+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]+)" "(?P<http_user_agent>[^"]+)" "(?P<http_x_forwarded_for>[^"]+)" rt=(?P<request_time>[^ ]+)'
      - labels:
          method:
          status:
          job:
          type:
      - timestamp:
          source: time_local
          format: '02/Jan/2006:15:04:05 -0700'

  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          type: error
          __path__: /var/log/nginx/error.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<pid>\d+).(?P<tid>\d+): (?P<message>.*)'
      - labels:
          level:
          job:
          type:
      - timestamp:
          source: timestamp
          format: '2006/01/02 15:04:05'

  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\w+ \d+ \d{2}:\d{2}:\d{2}) (?P<hostname>\w+) (?P<service>\w+)\[(?P<pid>\d+)\]: (?P<message>.*)'
      - labels:
          hostname:
          service:
          job:
      - timestamp:
          source: timestamp
          format: 'Jan 2 15:04:05'
